package ru.practicum.android.diploma.util

const val REGION_ID_KEY = "REGION_ID_KEY"
const val PLACE_OF_WORK_KEY = "PLACE_OF_WORK_KEY"
const val PLACE_OF_WORK_COUNTRY_KEY = "PLACE_OF_WORK_COUNTRY_KEY"
const val PLACE_OF_WORK_REGION_KEY = "PLACE_OF_WORK_REGION_KEY"
const val COUNTRY_REQUEST_KEY = "COUNTRY_REQUEST_KEY"
const val COUNTRY_BUNDLE_KEY = "COUNTRY_BUNDLE_KEY"
const val FILTER_REQUEST_KEY = "FILTER_REQUEST_KEY"
const val FILTER_BUNDLE_KEY = "FILTER_BUNDLE_KEY"
const val FILTER_TO_PLACE_OF_WORK_KEY = "FILTER_TO_PLACE_OF_WORK_KEY"
const val FILTER_TO_PLACE_OF_WORK_COUNTRY_KEY = "FILTER_TO_PLACE_OF_WORK_COUNTRY_KEY"
const val FILTER_TO_PLACE_OF_WORK_REGION_KEY = "FILTER_TO_PLACE_OF_WORK_REGION_KEY"
const val REGION_REQUEST_KEY = "REGION_REQUEST_KEY"
const val REGION_BUNDLE_KEY = "REGION_BUNDLE_KEY"

